import React,{useEffect,useState} from 'react';
import {api,json} from './api.js';
import {Field,FormNote} from './forms.jsx';
export function CertificatesPage(){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{api('/certificates').then(setData).catch(e=>setError(e.message))},[]);
 async function save(action,body={}){setBusy(true);setError('');setNotice('');try{setData(await api('/certificates/'+action,json('POST',body)));setNotice('Certificate staged. Configure the bundle path and restart the server to activate it.');}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function replace(event){event.preventDefault();const form=event.currentTarget,values=new FormData(form);const cert=values.get('cert'),key=values.get('key');if(cert.size>20000||key.size>12000){setError('Certificate limit: 20 KB. Private key limit: 12 KB.');return;}await save('replace',{cert:await cert.text(),key:await key.text()});form.reset();}
 return <><p className="eyebrow">Administrator controls</p><h1>Certificates</h1><p className="subtitle">Prepare a temporary local HTTPS certificate and replace it when your issued certificate is available.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}<section className="panel"><h2>Connection and staged certificate</h2><p>Current server connection: {data?.secure?'HTTPS':'HTTP'}</p>{data?.staged?<><p>Certificate: {data.staged.kind==='temporary'?'Temporary development certificate':'Uploaded certificate'}{data.staged.selfSigned?' (self-signed)':''}</p><p>Expires: {data.staged.validTo}</p><p>Activation: {data.activeFingerprint===data.staged.fingerprint?'Matches the running server':'Pending server restart/configuration'}</p><p>Updated: {data.staged.updatedAt}</p></>:<p>No certificate staged.</p>}<p>Temporary certificates last 30 days and are not browser-trusted. They are for local demonstration. Keys are stored on the server and never returned by this page.</p><button className="primary" disabled={busy||data?.available===false||!data} onClick={()=>save('generate')}>{busy?'Saving...':'Generate temporary certificate'}</button></section><section className="panel"><h2>Replace certificate</h2><p>Upload matching PEM files covering localhost and 127.0.0.1. This replaces the staged pair; the running server keeps its current certificate until restarted.</p><form onSubmit={replace}><FormNote/><Field>Certificate chain (PEM)<input name="cert" type="file" accept=".pem,.crt" required/></Field><Field>Private key (PEM)<input name="key" type="file" accept=".pem,.key" required/></Field><button disabled={busy||data?.available===false||!data}>Stage replacement</button></form></section>{data?.bundlePath&&<section className="panel"><h2>Activate on this server</h2><p>Set AITRACE_TLS_BUNDLE_PATH to the path below, clear separate certificate/key settings, and restart AITrace. HTTPS applies to every organisation on this server.</p><p style={{overflowWrap:'anywhere'}}>{data.bundlePath}</p><p>Protect this directory using operating-system permissions. Use HTTPS when uploading replacement keys.</p></section>}</>;
}
