import React,{useEffect,useState} from 'react';
import {api,json} from './api.js';
import {Field} from './forms.jsx';

export const capabilities=['registry:create','registry:update','assessment:review','action:manage','report:export'];
const capabilityLabels={'registry:create':'Register AI uses','registry:update':'Maintain registry records','assessment:review':'Review assessments','action:manage':'Manage actions','report:export':'View and export reports'};
const workflowDefaults={allowLinkedActions:true,mandatoryPolicyReading:false,requireInProgressBeforeCompletion:false,allowReopen:true};
const workflowOptions=[
 {key:'mandatoryPolicyReading',stage:'01 · Assessment evidence',label:'Require policy acknowledgement before submission',description:'Ask the submitting person to confirm that they have read the policy versions attached to their assessment.',on:'Submission is blocked until that person acknowledges every required policy version.',off:'Policy links remain available without a required reading acknowledgement.',example:'A later policy upload does not replace the version already attached to a draft.',scope:'New assessment drafts after activation. Link at least one policy to an assessment topic first; otherwise new drafts are blocked.'},
 {key:'allowLinkedActions',stage:'02 · Follow-up work',label:'Allow new assessment-linked actions',description:'Let managers connect a follow-up action to a submitted assessment so the decision and the work stay traceable.',on:'Managers can create an action with the assessment and AI use linked.',off:'New actions cannot be linked to an assessment. Standalone actions for an AI use remain available.',example:'Create an action to obtain evidence after reviewing an assessment.',scope:'New assessment links after activation. Existing linked actions keep their references.'},
 {key:'requireInProgressBeforeCompletion',stage:'03 · Action completion',label:'Require In Progress before action completion',description:'Choose whether owners must record that work has started before they can mark it complete.',on:'Not Started → In Progress → Complete. Direct completion is rejected.',off:'An action may move directly from Not Started to Complete.',example:'Turn this on when recording the start of work is part of your process.',scope:'Actions created after activation. Each action keeps the transition rules it was created with.'},
 {key:'allowReopen',stage:'04 · Further work',label:'Allow completed actions to reopen',description:'Choose whether completed work can be returned to an open status when more follow-up is needed.',on:'A completed action can return to Not Started or In Progress; the change is recorded in its history.',off:'Complete is the final state. Create a new action if further work is needed.',example:'Reopen an evidence-collection action when the supplied material needs updating.',scope:'Actions created after activation. Reopening does not change an assessment result.'}
];
const editable=(config,areas)=>({questions:config.questions,customRoles:config.customRoles,workflow:config.workflow,automationRules:config.automationRules||[],businessAreas:areas.split('\n').map(a=>a.trim()).filter(Boolean)});

export function GovernanceConfiguration(){
 const [config,setConfig]=useState(null),[history,setHistory]=useState([]),[events,setEvents]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [reference,setReference]=useState('Sponsor approval assumed at user direction (30 September 2026).'),[areas,setAreas]=useState(''),[section,setSection]=useState('requirements'),[saved,setSaved]=useState('');
 async function load(){const {history,events,...current}=await api('/governance-configuration'),next={...current,workflow:{...workflowDefaults,...current.workflow},automationRules:current.automationRules||[]},nextAreas=(current.businessAreas||[]).join('\n');setConfig(next);setAreas(nextAreas);setSaved(JSON.stringify(editable(next,nextAreas)));setHistory(history);setEvents(events);}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const dirty=config&&saved!==JSON.stringify(editable(config,areas));
 async function save(event){
  event.preventDefault();const activate=event.nativeEvent.submitter?.value==='activate';setError('');setNotice('');
  if(config.questions.some(q=>!q.label.trim())){setSection('requirements');setError('Give every assessment question its wording before saving.');return}
  if(config.customRoles.some(role=>!role.name.trim())){setSection('roles');setError('Give every capability role a name before saving.');return}
  setBusy(true);
  try{await api('/governance-configuration',json('PUT',{expectedVersion:config.version,...editable(config,areas),activate,expectedLifecycleRevision:config.lifecycleRevision,approvalReference:reference}));await load();setNotice(activate?'Configuration version saved and activated. Existing assessments and actions retain their snapshots.':'Draft version saved. The active configuration is unchanged.');}catch(e){setError(e.message)}finally{setBusy(false)}
 }
 async function lifecycle(version,action){setBusy(true);setError('');setNotice('');try{await api(`/governance-configuration/${version}/lifecycle`,json('POST',{action,reference,expectedLifecycleRevision:config.lifecycleRevision}));await load();setNotice(`Version ${version} ${action}. Existing records retain their snapshots.`);}catch(e){setError(e.message)}finally{setBusy(false)}}
 function question(index,patch){setConfig({...config,questions:config.questions.map((q,i)=>i===index?{...q,...patch}:q)})}
 function roleChange(index,patch){setConfig({...config,customRoles:config.customRoles.map((role,i)=>i===index?{...role,...patch}:role)})}
 return <div className="configuration-page"><p className="eyebrow">Administration / governance controls</p><h1>Governance configuration</h1><p className="subtitle">Shape the assessment and follow-up process. Prepare a version, review its settings and activate it for new work.</p>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {config&&<>
 <section className="panel configuration-status"><div><span className="config-badge">{config.activeVersion===null?'New work paused':config.activeVersion===0?'Baseline active':`Version ${config.activeVersion} active`}</span><h2>{config.activeVersion===null?'Activate a saved version to resume':'Your current governance setup'}</h2><p>Editing latest saved version {config.version}. {dirty?'You have unsaved changes.':'No unsaved changes.'}</p></div><div className="configuration-status-note"><strong>Save → Review → Activate</strong><p>Saving a draft prepares changes. Activation applies them to new work. Existing assessments, actions and role assignments keep their saved settings.</p></div></section>
 <div className="configuration-nav" role="group" aria-label="Configuration sections">{[['requirements','Assessment requirements'],['workflow','Workflow settings'],['roles','Custom capability roles'],['history','Version history']].map(([id,label])=><button key={id} type="button" aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}</div>
 <form onSubmit={save} noValidate>
 <fieldset className="configuration-editor" disabled={busy}><legend className="sr-only">Configuration editor</legend>
 {section==='requirements'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">01 / Evidence to collect</p><h2>Assessment requirements</h2><p className="form-note">Edit question wording and policy-link topics. Add up to twenty Yes/No evidence questions.</p></div><span className="config-badge">{config.questions.length} / 24 questions</span></div>
 <p className="config-callout">The four core questions feed the fixed synthetic demonstration scoring model. Additional questions collect evidence without changing scores.</p>
 <div className="question-grid">{config.questions.map((q,index)=><fieldset className="question-card" key={q.id}><legend>Question {index+1} <span>· {q.id.startsWith('additional-')?'Additional evidence':'Core scoring input'}</span></legend><Field>Question {index+1} wording<input required maxLength="240" value={q.label} onChange={e=>question(index,{label:e.target.value})}/></Field><Field>Question {index+1} policy topic<input maxLength="240" value={q.topic||''} onChange={e=>question(index,{topic:e.target.value})}/></Field>{q.id.startsWith('additional-')?<div className="question-options"><label className="capability-choice"><input type="checkbox" checked={q.required!==false} onChange={e=>question(index,{required:e.target.checked})}/>Required answer</label><button type="button" onClick={()=>setConfig({...config,questions:config.questions.filter((_,i)=>i!==index)})}>Remove additional question</button></div>:<p className="form-note">Required · retained in every definition</p>}</fieldset>)}</div>
 <button type="button" disabled={config.questions.length>=24} onClick={()=>setConfig({...config,questions:[...config.questions,{id:`additional-${crypto.randomUUID()}`,label:'',topic:'Additional governance evidence',required:true}]})}>Add evidence question</button>
 <div className="configuration-scope"><div><h3>Where this assessment applies</h3><p>Leave blank for every business area, or enter the exact Registry names to limit new assessments to those areas.</p></div><Field>Applicable business areas (one per line)<textarea value={areas} onChange={e=>setAreas(e.target.value)} placeholder={'Operations\nFinance'}/></Field></div>
 </section>}
 {section==='workflow'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">02 / How work moves</p><h2>Workflow settings</h2><p className="form-note">Configure four supported controls. The preview below reflects your edits; save and activate to apply them.</p></div><span className="config-badge">Versioned rules</span></div>
 <div className="workflow-preview" aria-label="Workflow preview" aria-live="polite"><div><span>Assessment</span><strong>Draft</strong><small>{config.workflow.mandatoryPolicyReading?'Acknowledge linked policy versions → Submit':'Complete required answers → Submit'}</small></div><span className="workflow-arrow" aria-hidden="true">→</span><div><span>Follow-up</span><strong>{config.workflow.allowLinkedActions?'Linked action available':'Standalone action only'}</strong><small>Managers assign an owner and due date</small></div><span className="workflow-arrow" aria-hidden="true">→</span><div><span>Action progress</span><strong>{config.workflow.requireInProgressBeforeCompletion?'Not Started → In Progress → Complete':'Not Started → Complete allowed'}</strong><small>{config.workflow.allowReopen?'Completed actions may reopen':'Completion is final for the action'}</small></div></div>
 <div className="automation-builder"><div className="section-heading"><div><h3>When this happens, create follow-up work</h3><p className="form-note">These bounded rules run after a submitted assessment. They can create an owned action with a due date; arbitrary scripts and states are not available.</p></div><button type="button" onClick={()=>setConfig({...config,automationRules:[...(config.automationRules||[]),{id:`automation-${crypto.randomUUID()}`,name:'',event:'assessment.submitted',outcome:'',title:'',dueDays:7}]})}>Add automation rule</button></div>{(config.automationRules||[]).map((rule,index)=><fieldset className="automation-card" key={rule.id}><legend>Rule {index+1}</legend><Field>Rule name<input required maxLength="100" value={rule.name} onChange={e=>setConfig({...config,automationRules:config.automationRules.map((r,i)=>i===index?{...r,name:e.target.value}:r)})}/></Field><Field>When<select value={rule.event} onChange={e=>setConfig({...config,automationRules:config.automationRules.map((r,i)=>i===index?{...r,event:e.target.value}:r)})}><option value="assessment.submitted">Assessment is submitted</option></select></Field><Field>Only when result is<select value={rule.outcome||''} onChange={e=>setConfig({...config,automationRules:config.automationRules.map((r,i)=>i===index?{...r,outcome:e.target.value}:r)})}><option value="">Any synthetic result</option><option>High (demo)</option><option>Medium (demo)</option><option>Low (demo)</option></select></Field><Field>Then create action<input required maxLength="200" value={rule.title} onChange={e=>setConfig({...config,automationRules:config.automationRules.map((r,i)=>i===index?{...r,title:e.target.value}:r)})}/></Field><Field>Due in days<input type="number" min="0" max="365" required value={rule.dueDays} onChange={e=>setConfig({...config,automationRules:config.automationRules.map((r,i)=>i===index?{...r,dueDays:Number(e.target.value)}:r)})}/></Field><button type="button" onClick={()=>setConfig({...config,automationRules:config.automationRules.filter((_,i)=>i!==index)})}>Remove rule</button></fieldset>)}</div>
<div className="workflow-grid">{workflowOptions.map(option=><article className="workflow-card" key={option.key}><p className="eyebrow">{option.stage}</p><label className="workflow-control"><strong>{option.label}</strong><input type="checkbox" aria-describedby={`${option.key}-description`} checked={config.workflow[option.key]} onChange={e=>setConfig({...config,workflow:{...config.workflow,[option.key]:e.target.checked}})}/></label><p id={`${option.key}-description`}>{option.description}</p><div className="workflow-effect"><span className="config-badge">{config.workflow[option.key]?'Enabled':'Disabled'}</span><p>{config.workflow[option.key]?option.on:option.off}</p></div><dl><dt>Example</dt><dd>{option.example}</dd><dt>Applies to</dt><dd>{option.scope}</dd></dl></article>)}</div>
 </section>}
 {section==='roles'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">03 / Who can do the work</p><h2>Custom capability roles</h2><p className="form-note">Add selected capabilities to an account's fixed role. Assign these templates from Accounts after activation.</p></div><span className="config-badge">{config.customRoles.length} / 12 templates</span></div>
 <p className="config-callout">Templates cannot grant administration. Existing assignments keep their selected version until you explicitly reassign them.</p>
 {!config.customRoles.length&&<div className="config-empty"><h3>Your fixed roles are ready to use</h3><p>Add a capability role when a team needs a specific combination of additional permissions.</p></div>}
 <div className="question-grid">{config.customRoles.map((role,index)=><fieldset className="question-card" key={role.id}><legend>{role.name||'New capability role'}</legend><Field>Role name<input required maxLength="80" value={role.name} onChange={e=>roleChange(index,{name:e.target.value})}/></Field>{capabilities.map(permission=><label className="capability-choice" key={permission}><input type="checkbox" checked={role.permissions.includes(permission)} onChange={e=>roleChange(index,{permissions:e.target.checked?[...role.permissions,permission]:role.permissions.filter(p=>p!==permission)})}/>{capabilityLabels[permission]}</label>)}<button type="button" onClick={()=>setConfig({...config,customRoles:config.customRoles.filter((_,i)=>i!==index)})}>Retire {role.name||'role'}</button></fieldset>)}</div><button type="button" disabled={config.customRoles.length>=12} onClick={()=>setConfig({...config,customRoles:[...config.customRoles,{id:`custom-${crypto.randomUUID()}`,name:'',permissions:[]}]})}>Add capability role</button>
 </section>}
 {section==='history'&&<section className="panel"><p className="eyebrow">04 / Decisions and versions</p><h2>Configuration history</h2><p className="form-note">Review saved versions and activate one using the change reference below. Activating an older version applies it to new work.</p>
 {dirty&&<p className="notice">Save your edits before activating or retiring a version.</p>}
 <div className="configuration-history">{history.length?history.map(row=>{const previous=JSON.parse(row.configuration_json);return <details key={row.version}><summary>Version {row.version} / {row.created_at}</summary><p>{previous.questions.length} questions · {(previous.customRoles||[]).length} capability roles · {(previous.businessAreas||[]).join(', ')||'All business areas'}</p><p>Administrator account: {row.actor_id}</p><ul>{workflowOptions.map(option=><li key={option.key}>{option.label}: {(previous.workflow?.[option.key]??workflowDefaults[option.key])?'Enabled':'Disabled'}</li>)}</ul><details><summary>Assessment questions and roles</summary><ol>{previous.questions.map(q=><li key={q.id}>{q.label} · {q.required===false?'Optional':'Required'} · {q.topic||'No topic'}</li>)}</ol><ul>{(previous.customRoles||[]).map(role=><li key={role.id}>{role.name}: {role.permissions.map(p=>capabilityLabels[p]||p).join(', ')||'No additional capabilities'}</li>)}</ul></details><button type="button" disabled={busy||dirty||!reference.trim()||config.activeVersion===row.version} onClick={()=>lifecycle(row.version,'activated')}>Activate version {row.version}</button></details>}):<p>Using the fixed demonstration baseline. Save a version to start the history.</p>}</div>
 <h3>Activation audit</h3>{events.length?<ol className="audit-timeline">{events.map(event=><li key={event.id}><strong>Version {event.version} {event.action}</strong><span>{event.created_at} · Account {event.actor_id}</span><p>{event.reference}</p></li>)}</ol>:<p className="form-note">No activation changes recorded.</p>}
 <div className="retirement-panel"><h3>Pause new work</h3><p>Retiring the active version blocks new assessments and actions until a saved version is activated again. Existing work remains available.</p>{config.activeVersion>0&&<button type="button" disabled={busy||dirty||!reference.trim()} onClick={()=>lifecycle(config.activeVersion,'retired')}>Retire active version</button>}</div>
 </section>}
 </fieldset>
 <section className="panel configuration-publish" aria-label="Save configuration"><div><h2>Save your configuration</h2><p>{dirty?'Your edits will become a new version.':'Save a new version or choose a saved version from History.'} The change reference is recorded with activation and retirement.</p><Field>Approval or change reference<input value={reference} maxLength="500" disabled={busy} onChange={e=>setReference(e.target.value)}/></Field></div><div><div className="actions"><button disabled={busy||!reference.trim()} value="draft">Save draft version</button><button className="primary" disabled={busy||!reference.trim()} value="activate">Save and activate version</button></div><p className="form-note">Draft: prepare for review. Activate: use for new work.</p></div></section>
 </form>
 </>}
 </div>;
}
