import React,{useEffect,useState} from 'react';
import {api,json} from './api.js';
import {Field} from './forms.jsx';
export const capabilities=['registry:create','registry:update','assessment:review','action:manage','report:export'];
const workflowDefaults={allowLinkedActions:true,mandatoryPolicyReading:false,requireInProgressBeforeCompletion:false,allowReopen:true};
export function GovernanceConfiguration(){
  const [config,setConfig]=useState(null),[history,setHistory]=useState([]),[events,setEvents]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [reference,setReference]=useState('Sponsor approval assumed at user direction (30 September 2026).'),[areas,setAreas]=useState('');
  async function load(){const {history,events,...current}=await api('/governance-configuration');setConfig({...current,workflow:{...workflowDefaults,...current.workflow}});setAreas((current.businessAreas||[]).join('\n'));setHistory(history);setEvents(events);}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  async function save(event){
    event.preventDefault();const activate=event.nativeEvent.submitter?.value==='activate';setBusy(true);setError('');setNotice('');
    try{await api('/governance-configuration',json('PUT',{expectedVersion:config.version,questions:config.questions,businessAreas:areas.split('\n').map(a=>a.trim()).filter(Boolean),customRoles:config.customRoles,workflow:config.workflow,activate,expectedLifecycleRevision:config.lifecycleRevision,approvalReference:reference}));await load();setNotice(activate?'Configuration version saved and activated. Existing assessments and actions retain their snapshots.':'Draft version saved. The active configuration is unchanged.');}catch(e){setError(e.message)}finally{setBusy(false)}
  }
  async function lifecycle(version,action){setBusy(true);setError('');setNotice('');try{await api(`/governance-configuration/${version}/lifecycle`,json('POST',{action,reference,expectedLifecycleRevision:config.lifecycleRevision}));await load();setNotice(`Version ${version} ${action}. Existing records retain their snapshots.`);}catch(e){setError(e.message)}finally{setBusy(false)}}
  function question(index,patch){setConfig({...config,questions:config.questions.map((q,i)=>i===index?{...q,...patch}:q)})}
  return <><h1>Governance configuration</h1><p className="subtitle">Sponsor approval is assumed at the user's direction for this implementation. Scoring remains the fixed synthetic demonstration model; extra questions collect evidence without changing scores.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}{config&&<>
    <section className="panel"><h2>Activation</h2><p>Active version: {config.activeVersion===null?'Retired - new assessments and actions are paused':config.activeVersion===0?'Built-in baseline':config.activeVersion}. Latest saved version: {config.version}.</p><Field>Approval or change reference<input value={reference} maxLength="500" onChange={e=>setReference(e.target.value)}/></Field><p>Activation applies to future drafts, actions and role assignments. Retirement pauses new assessments and actions; existing work remains available.</p>{config.activeVersion>0&&<button disabled={busy||!reference.trim()} onClick={()=>lifecycle(config.activeVersion,'retired')}>Retire active version</button>}</section>
    <form onSubmit={save}><section className="panel"><h2>Assessment requirements</h2><p>The four scoring questions remain required. Additional Yes/No questions can be optional or required. Topics support policy links.</p>{config.questions.map((q,index)=><fieldset key={q.id}><legend>{q.id}</legend><Field>{q.id}<input required maxLength="240" value={q.label} onChange={e=>question(index,{label:e.target.value})}/></Field><Field>Topic for {q.id}<input maxLength="240" value={q.topic||''} onChange={e=>question(index,{topic:e.target.value})}/></Field>{q.id.startsWith('additional-')&&<><label className="capability-choice"><input type="checkbox" checked={q.required!==false} onChange={e=>question(index,{required:e.target.checked})}/>Required answer</label><button type="button" onClick={()=>setConfig({...config,questions:config.questions.filter((_,i)=>i!==index)})}>Remove additional question</button></>}</fieldset>)}<button type="button" disabled={config.questions.length>=24} onClick={()=>setConfig({...config,questions:[...config.questions,{id:`additional-${crypto.randomUUID()}`,label:'',topic:'Additional governance evidence',required:true}]})}>Add evidence question</button><Field>Applicable business areas (one per line)<textarea value={areas} onChange={e=>setAreas(e.target.value)}/></Field><p>Leave blank to apply to all business areas. Names must match the registry exactly.</p></section>
    <section className="panel"><h2>Custom capability roles</h2><p>Optional additions to a fixed role. Templates cannot grant administration. Assignments keep their selected version until explicitly reassigned.</p>{config.customRoles.map((role,index)=><fieldset key={role.id}><legend>{role.id}</legend><Field>Role name<input required maxLength="80" value={role.name} onChange={e=>setConfig({...config,customRoles:config.customRoles.map((r,i)=>i===index?{...r,name:e.target.value}:r)})}/></Field>{capabilities.map(permission=><label className="capability-choice" key={permission}><input type="checkbox" checked={role.permissions.includes(permission)} onChange={e=>setConfig({...config,customRoles:config.customRoles.map((r,i)=>i===index?{...r,permissions:e.target.checked?[...r.permissions,permission]:r.permissions.filter(p=>p!==permission)}:r)})}/>{permission}</label>)}<button type="button" onClick={()=>setConfig({...config,customRoles:config.customRoles.filter((_,i)=>i!==index)})}>Retire {role.name||'role'}</button></fieldset>)}<button type="button" disabled={config.customRoles.length>=12} onClick={()=>setConfig({...config,customRoles:[...config.customRoles,{id:`custom-${crypto.randomUUID()}`,name:'',permissions:[]}]})}>Add capability role</button></section>
    <section className="panel"><h2>Workflow settings</h2>{[{key:'allowLinkedActions',label:'Allow new assessment-linked actions'},{key:'mandatoryPolicyReading',label:'Require policy acknowledgement before submission'},{key:'requireInProgressBeforeCompletion',label:'Require In Progress before action completion'},{key:'allowReopen',label:'Allow completed actions to reopen'}].map(({key,label})=><label className="capability-choice" key={key}><input type="checkbox" checked={config.workflow[key]} onChange={e=>setConfig({...config,workflow:{...config.workflow,[key]:e.target.checked}})}/>{label}</label>)}<p>New drafts capture current versions of policies linked to their question topics. Each submitting user must acknowledge those versions. No linked policies means new drafts are blocked when acknowledgement is required. Existing drafts retain their requirements.</p><p>Action transition settings are captured when an action is created. Later configuration changes do not rewrite its workflow or completion history.</p></section>
    <div className="actions"><button disabled={busy||!reference.trim()} value="draft">Save draft version</button><button className="primary" disabled={busy||!reference.trim()} value="activate">Save and activate version</button></div></form></>}
    <section className="panel"><h2>Configuration history</h2>{history.length?history.map(row=><details key={row.version}><summary>Version {row.version} / {row.created_at}</summary><p>Administrator account: {row.actor_id}</p><button disabled={busy||!reference.trim()||config.activeVersion===row.version} onClick={()=>lifecycle(row.version,'activated')}>Activate version {row.version}</button><pre className="config-history">{JSON.stringify(JSON.parse(row.configuration_json),null,2)}</pre></details>):<p>Using the fixed demonstration baseline.</p>}<h3>Activation audit</h3>{events.map(event=><p className="history-entry" key={event.id}>{event.created_at}: version {event.version} {event.action} by {event.actor_id}. Reference: {event.reference}</p>)}</section></>;
}
