function dueLabel(action, asOfDate){
  if(action.dueDate<asOfDate)return 'Overdue';
  if(action.dueDate===asOfDate)return 'Due today';
  return `Due ${action.dueDate}`;
}

export function OverviewPage({overview,onNavigate}){
  const registry=overview?.registry??{total:0,notAssessed:0,byCategory:{}},drafts=overview?.drafts??{total:0,items:[]},dueActions=overview?.dueActions??[],asOfDate=overview?.filter?.asOfDate??new Date().toISOString().slice(0,10);
  return <><p className="eyebrow">Organisation governance overview</p><h1>AI use at a glance</h1><p className="subtitle">Your point-in-time view of AI use, assessment work and governance follow-up.</p>
    <div className="stat-grid"><article className="stat-card"><span>Recorded uses</span><strong>{registry.total}</strong></article><article className="stat-card"><span>Draft assessments</span><strong>{drafts.total}</strong><small>Saved work still to submit</small></article><article className="stat-card"><span>Outstanding actions</span><strong>{overview?.actions?.status==='available'?overview.actions.outstanding:(overview?.openActions?.total??0)}</strong><small>{overview?.actions?.status==='available'?`${overview.actions.overdue} overdue`:'Your assigned work'}</small></article></div>
    <section className="panel"><div className="section-heading"><div><p className="eyebrow">Daily work</p><h2>What needs attention</h2><p className="form-note">As at {asOfDate}</p></div><div className="actions"><button onClick={()=>onNavigate('assessments')}>Open assessments</button><button onClick={()=>onNavigate('actions')}>Open actions</button></div></div>
      <div className="daily-work-grid"><section><h3>Draft assessments</h3>{drafts.items.length?<ul className="work-list">{drafts.items.map(item=><li key={item.id}><strong>{item.aiUseName}</strong><span>Updated {item.updatedAt.slice(0,10)}</span></li>)}</ul>:<p className="form-note">No draft assessments need attention.</p>}</section><section><h3>Due actions</h3>{dueActions.length?<ul className="work-list">{dueActions.map(action=><li key={action.id}><strong>{action.title}</strong><span>{action.aiUseName} · {dueLabel(action,asOfDate)}</span></li>)}</ul>:<p className="form-note">No open actions are currently due.</p>}</section></div>
    </section>
    <section className="panel"><h2>Governance follow-up</h2><p className="form-note">Risk results use demonstration rules and do not certify compliance.</p><div className="actions"><button onClick={()=>onNavigate('registry')}>Open registry</button><button onClick={()=>onNavigate('policies')}>View policies</button><button onClick={()=>onNavigate('notifications')}>View notifications</button></div>{overview?.risk?.status==='available'&&<div className="risk-summary">{overview.risk.byOutcome.map(r=><span className={`status risk-${r.id}`} key={r.id}>{r.label}: {r.count}</span>)}{!overview.risk.total&&<p>No completed assessments yet.</p>}</div>}{overview?.policies?.status==='available'&&<p className="form-note">{overview.policies.total} current policies; {overview.policies.overdue||0} overdue reviews.</p>}</section>
    <div className="overview-grid"><section className="panel"><p className="eyebrow">Across your organisation</p><h2>AI use by business area</h2>{Object.entries(registry.byCategory||{}).map(([area,count])=><div className="area" key={area}><div><span>{area}</span><strong>{count} {count===1?'use':'uses'} · {registry.total?Math.round(count/registry.total*100):0}%</strong></div><div className="bar"><span style={{width:`${count/Math.max(registry.total,1)*100}%`}}/></div></div>)}{!registry.total&&<div className="empty"><h3>Your overview starts here</h3><p>Add your first AI use to see which parts of your business are using AI.</p></div>}</section><section className="panel next-step"><p className="eyebrow">Your next step</p><h2>Make AI use visible</h2><p>A useful register starts with the basics: the tool, the person responsible, and the data it handles.</p><button className="primary" onClick={()=>onNavigate('registry')}>Open the registry</button><button className="text-button" onClick={()=>onNavigate('guide')}>Read the getting started guide</button></section></div>
  </>;
}
