import React,{useEffect,useState} from 'react';
import {api} from './api.js';

export function ReportsPage(){
 const today=new Date().toISOString().slice(0,10),[date,setDate]=useState(today),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(value=date){setBusy(true);try{setData(await api(`/reports/snapshot?asOfDate=${encodeURIComponent(value)}`));setError('')}catch(e){setData(null);setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function download(format){try{const blob=await api(`/reports/compliance.${format}?asOfDate=${encodeURIComponent(data.asOfDate)}`),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`aitrace-governance-${data.asOfDate}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e.message)}}
 return <><p className="eyebrow">Historical governance reporting</p><h1>Reports</h1><p className="subtitle">Reconstruct recorded AI uses, assessments, actions and policy reviews at the end of a selected UTC day. CSV and PDF exports use the same date. Today's view changes as records are saved.</p>{error&&<p className="error" role="alert">{error}</p>}<section className="panel"><div className="actions"><label className="field">As at date<input type="date" max={today} value={date} onChange={e=>setDate(e.target.value)}/></label><button disabled={busy||!date} onClick={()=>load()}>{busy?'Loading...':'Refresh view'}</button><button disabled={busy||!data||data.asOfDate!==date} onClick={()=>download('csv')}>Export CSV</button><button className="primary" disabled={busy||!data||data.asOfDate!==date} onClick={()=>download('pdf')}>Export PDF</button></div>{data&&<><p>History captured from {data.coverageStart}. Earlier states are unavailable.</p><p>Showing {data.asOfDate} (UTC).</p><div className="stat-grid"><article className="stat-card"><span>Recorded uses</span><strong>{data.registry.total}</strong></article><article className="stat-card"><span>Not assessed</span><strong>{data.registry.notAssessed}</strong></article><article className="stat-card"><span>Outstanding actions</span><strong>{data.actions.outstanding}</strong><small>{data.actions.overdue} overdue</small></article></div></>}</section></>;
}
