import React,{useEffect,useState} from 'react';
import {api,json} from './api.js';
import {Field,FormNote} from './forms.jsx';
export function AssessmentsPage({records,onChanged}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[responses,setResponses]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>setItems((await api('/assessments')).assessments);
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const select=item=>{setSelected(item);setResponses(item.responses);setNotice('');setError('')};
 async function create(event){event.preventDefault();setBusy(true);setError('');try{const item=await api('/assessments',json('POST',Object.fromEntries(new FormData(event.currentTarget))));select(item);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(submit){setBusy(true);setError('');try{const item=await api(`/assessments/${selected.id}`,json('PUT',{expectedRevision:selected.revision,responses,submit}));select(item);await load();await onChanged();setNotice(submit?'Assessment submitted. Results are demonstration-only.':'Draft saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><p className="eyebrow">Assess and understand</p><h1>Assessments</h1><p className="subtitle">Review an AI use, save a draft, and understand the reasons behind its risk result.</p><p className="notice">Demonstration questions and rules. Sponsor-approved content is still pending; results are not compliance approval.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <section className="panel"><h2>Start an assessment</h2><form className="record-form" onSubmit={create}><Field>AI use<select name="aiUseId" required defaultValue=""><option value="" disabled>Choose a registered AI use</option>{records.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><button className="primary" disabled={busy||!records.length}>Start assessment</button></form>{!records.length&&<p className="form-note">Register or disclose an AI tool first.</p>}</section>
 {selected&&<section className="panel"><h2>{selected.state==='Draft'?'Assessment questions':'Assessment result'}</h2><p className="form-note">Definition {selected.definition.id} / v{selected.definition.version} · revision {selected.revision}</p>{selected.state==='Draft'?<form className="admin-form" onSubmit={e=>{e.preventDefault();save(true)}}><FormNote/>{selected.definition.questions.map(q=><div key={q.id}><Field>{q.label}<select required value={responses[q.id]===undefined?'':String(responses[q.id])} onChange={e=>setResponses({...responses,[q.id]:e.target.value==='true'})}><option value="" disabled>Choose an answer</option><option value="true">Yes</option><option value="false">No</option></select></Field><p className="form-note">{q.topic}</p></div>)}<div className="actions"><button type="button" disabled={busy} onClick={()=>save(false)}>Save draft</button><button className="primary" disabled={busy}>Submit assessment</button></div></form>:<><p className="notice">{selected.result.outcome.label}</p><ul>{selected.result.triggeredRules.map(r=><li key={r.id}>{r.explanation}</li>)}</ul><h3>Suggested follow-up actions</h3><ul>{selected.result.actions.map(a=><li key={a.id}>{a.label}</li>)}</ul>{!selected.result.actions.length&&<p>No follow-up actions were suggested by the demo rules.</p>}<details><summary>Submitted answers and source trace</summary>{selected.definition.questions.map(q=><p key={q.id}>{q.label} <strong>{selected.responses[q.id]?'Yes':'No'}</strong></p>)}{selected.definition.sources.map(s=><p key={s.id}>{s.reference}</p>)}</details></>}</section>}
 <section className="panel"><h2>Assessment history</h2><div className="table-wrap"><table><thead><tr><th>AI use</th><th>Status</th><th>Risk</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{records.find(r=>r.id===item.ai_use_id)?.name||'AI use'}</td><td>{item.state}</td><td>{item.result?.outcome.label||'Not assessed'}</td><td><button onClick={()=>select(item)}>Open assessment</button></td></tr>)}</tbody></table></div>{!items.length&&<p className="empty">No assessments yet.</p>}</section></>;
}
