import React,{useEffect,useState} from 'react';
import {api,json} from './api.js';
import {Field,FormNote} from './forms.jsx';
export function AssessmentsPage({records,onChanged}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[responses,setResponses]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>setItems((await api('/assessments')).assessments);
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const select=item=>{setSelected(item);setResponses(item.responses);setNotice('');setError('')};
 async function create(event){event.preventDefault();setBusy(true);setError('');try{const item=await api('/assessments',json('POST',Object.fromEntries(new FormData(event.currentTarget))));select(item);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(submit){setBusy(true);setError('');try{const item=await api(`/assessments/${selected.id}`,json('PUT',{expectedRevision:selected.revision,responses,submit}));select(item);await load();await onChanged();setNotice(submit?'Assessment submitted. Results are demonstration-only.':'Draft saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><p className="eyebrow">Assess and understand</p><h1>Assessments</h1><p className="subtitle">Review an AI use, save a draft, and understand the reasons behind its risk result.</p><p className="notice">Demonstration questions and rules. Sponsor-approved content is still pending; results are not compliance approval.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 <section className="panel"><h2>Start an assessment</h2><form className="record-form" onSubmit={create}><Field>AI use<select name="aiUseId" required defaultValue=""><option value="" disabled>Choose a registered AI use</option>{records.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><button className="primary" disabled={busy||!records.length}>Start assessment</button></form>{!records.length&&<p className="form-note">Register or disclose an AI tool first.</p>}</section>
 {selected&&<section className="panel"><h2>{selected.state==='Draft'?'Assessment questions':'Assessment result'}</h2><p className="form-note">Definition {selected.definition.id} / v{selected.definition.version} · revision {selected.revision}</p>{selected.state==='Draft'?<form className="admin-form" onSubmit={e=>{e.preventDefault();save(true)}}><FormNote/>{selected.definition.questions.map(q=><div key={q.id}><Field>{q.label}<select required value={responses[q.id]===undefined?'':String(responses[q.id])} onChange={e=>setResponses({...responses,[q.id]:e.target.value==='true'})}><option value="" disabled>Choose an answer</option><option value="true">Yes</option><option value="false">No</option></select></Field><p className="form-note">{q.topic}</p></div>)}<div className="actions"><button type="button" disabled={busy} onClick={()=>save(false)}>Save draft</button><button className="primary" disabled={busy}>Submit assessment</button></div></form>:<><p className="notice">{selected.result.outcome.label}</p><ul>{selected.result.triggeredRules.map(r=><li key={r.id}>{r.explanation}</li>)}</ul><h3>Suggested follow-up actions</h3><ul>{selected.result.actions.map(a=><li key={a.id}>{a.label}</li>)}</ul>{!selected.result.actions.length&&<p>No follow-up actions were suggested by the demo rules.</p>}<details><summary>Submitted answers and source trace</summary>{selected.definition.questions.map(q=><p key={q.id}>{q.label} <strong>{selected.responses[q.id]?'Yes':'No'}</strong></p>)}{selected.definition.sources.map(s=><p key={s.id}>{s.reference}</p>)}</details></>}</section>}
 <section className="panel"><h2>Assessment history</h2><div className="table-wrap"><table><thead><tr><th>AI use</th><th>Status</th><th>Risk</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{records.find(r=>r.id===item.ai_use_id)?.name||'AI use'}</td><td>{item.state}</td><td>{item.result?.outcome.label||'Not assessed'}</td><td><button onClick={()=>select(item)}>Open assessment</button></td></tr>)}</tbody></table></div>{!items.length&&<p className="empty">No assessments yet.</p>}</section></>;
}

export function ActionsPage({principal,records,onChanged}){
 const canManage=principal.permissions.includes('action:manage');
 const [items,setItems]=useState([]),[owners,setOwners]=useState([]),[assessments,setAssessments]=useState([]),[editing,setEditing]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('');
 async function load(){setItems((await api('/actions')).actions);if(canManage){setOwners((await api('/action-owners')).accounts);setAssessments((await api('/assessments')).assessments.filter(a=>a.state==='Submitted'));}}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function submit(event){event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try{if(editing?.id){await api(`/actions/${editing.id}`,json('PUT',{expectedVersion:editing.version,title:values.title,dueDate:values.dueDate,ownerAccountId:values.ownerAccountId,status:values.status}));}else{if(!values.assessmentId)delete values.assessmentId;await api('/actions',json('POST',values));}setEditing(null);await load();await onChanged();}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><p className="eyebrow">Follow up and improve</p><h1>Actions</h1><p className="subtitle">{canManage?'Assign responsibilities, track due dates, and record progress.':'Your assigned compliance actions.'}</p>{error&&<p className="error" role="alert">{error}</p>}
 {canManage&&<section className="panel"><h2>{editing?'Edit action':'Create action'}</h2><form className="record-form" onSubmit={submit} key={editing?.id||'new'}><FormNote/>{!editing&&<><Field>AI use<select name="aiUseId" required><option value="">Choose an AI use</option>{records.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></Field><Field>Assessment link (optional)<select name="assessmentId"><option value="">No assessment link</option>{assessments.map(a=><option key={a.id} value={a.id}>{records.find(r=>r.id===a.ai_use_id)?.name} / {a.result.outcome.label} / {a.id.slice(0,8)}</option>)}</select></Field></>}<Field>Action title<input name="title" defaultValue={editing?.title||''} required maxLength="240"/></Field><Field>Assigned account<select name="ownerAccountId" required defaultValue={editing?.ownerAccountId||''}><option value="">Choose an owner</option>{owners.map(o=><option key={o.id} value={o.id}>{o.displayName}</option>)}</select></Field><Field>Due date<input type="date" name="dueDate" required defaultValue={editing?.dueDate||''}/></Field>{editing&&<Field>Action status<select name="status" defaultValue={editing.status}><option>Not Started</option><option>In Progress</option><option>Complete</option></select></Field>}<div className="actions">{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancel edit</button>}<button className="primary" disabled={busy}>{editing?'Save action':'Create action'}</button></div></form></section>}
 <section className="panel"><h2>{canManage?'Action register':'My actions'}</h2><Field>Filter by status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option>Not Started</option><option>In Progress</option><option>Complete</option></select></Field><div className="table-wrap"><table><thead><tr><th>Action</th><th>Owner</th><th>Due</th><th>Status</th><th>History</th></tr></thead><tbody>{items.filter(a=>!filter||a.status===filter).map(a=><tr key={a.id}><td>{a.title}<small>{records.find(r=>r.id===a.aiUseId)?.name}</small>{canManage&&<button onClick={()=>setEditing(a)}>Edit action</button>}</td><td>{a.owner}</td><td>{a.dueDate}{a.status!=='Complete'&&a.dueDate<new Date().toISOString().slice(0,10)&&<small>Overdue</small>}</td><td>{a.status}</td><td><details><summary>View history</summary>{a.history.map(h=><p key={h.version}>{h.changedAt}: {h.changes.map(c=>`${c.field}: ${c.to}`).join('; ')}</p>)}</details></td></tr>)}</tbody></table></div>{!items.length&&<p className="empty">No actions to show.</p>}</section></>;
}

export function PoliciesPage({principal}){
 const manage=principal.permissions.includes('action:manage');
 const [data,setData]=useState({policies:[],questions:[]}),[owners,setOwners]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(null);
 async function load(){setData(await api('/policies'));if(manage)setOwners((await api('/action-owners')).accounts)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function upload(event){event.preventDefault();const form=event.currentTarget,values=new FormData(form),file=values.get('file');setBusy(true);setError('');setNotice('');try{
  if(file.size>1048576)throw new Error('The file must be at most 1 MiB.');
  const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(new Error('File could not be read.'));reader.readAsDataURL(file)});
  await api('/policies',json('POST',{title:values.get('title'),filename:file.name,mediaType:file.name.toLowerCase().endsWith('.pdf')?'application/pdf':'text/plain',content,reviewerId:values.get('reviewerId'),reviewDue:values.get('reviewDue'),documentId:values.get('documentId')||undefined,checklist:values.getAll('checklist')}));form.reset();await load();setNotice('Policy version uploaded.');
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 async function markReview(event){event.preventDefault();setBusy(true);setError('');try{await api(`/policies/${review.id}/review`,json('POST',Object.fromEntries(new FormData(event.currentTarget))));setReview(null);await load();setNotice('Review recorded and next review scheduled.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const latest=data.policies.filter((p,i,all)=>all.findIndex(other=>other.document_id===p.document_id)===i);
 return <><p className="eyebrow">Evidence and guidance</p><h1>Policies</h1><p className="subtitle">Store internal guidance, link checklist topics, and schedule reviews. Downloads are available to your organisation.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {manage&&<section className="panel"><h2>Upload policy version</h2><p className="form-note">PDF or UTF-8 text, up to 1 MiB. Use fictional or de-identified material.</p><form className="record-form" onSubmit={upload}><FormNote/><Field>Policy title<input name="title" required maxLength="160"/></Field><Field>Version of<select name="documentId"><option value="">New policy document</option>{latest.map(p=><option key={p.id} value={p.document_id}>{p.title}</option>)}</select></Field><Field>Policy file<input name="file" type="file" accept=".pdf,.txt" required/></Field><Field>Reviewer<select name="reviewerId" required><option value="">Choose a reviewer</option>{owners.map(o=><option key={o.id} value={o.id}>{o.displayName}</option>)}</select></Field><Field>Review due<input type="date" name="reviewDue" required/></Field><fieldset className="checklist-options"><legend>Related checklist items (optional)</legend>{data.questions.map(q=><label key={q.id}><input type="checkbox" name="checklist" value={q.id}/>{q.label}</label>)}</fieldset><button className="primary" disabled={busy}>Upload policy</button></form></section>}
 {review&&<section className="panel"><h2>Record review: {review.title}</h2><form className="record-form" onSubmit={markReview}><Field>Next review due<input type="date" name="reviewDue" required/></Field><button className="primary" disabled={busy}>Record review</button></form></section>}
 <section className="panel"><h2>Policy library and versions</h2><div className="table-wrap"><table><thead><tr><th>Policy</th><th>Version</th><th>Review due</th><th>Checklist links</th><th>Actions</th></tr></thead><tbody>{data.policies.map(p=><tr key={p.id}><td>{p.title}<small>{p.filename}</small></td><td>{p.version}</td><td>{p.review_due}{p.reviewed_at&&<small>Reviewed {p.reviewed_at.slice(0,10)}</small>}</td><td>{p.checklist.join(', ')||'None'}</td><td><a href={`/api/policies/${p.id}/download`}>Download policy</a>{manage&&latest.includes(p)&&<button onClick={()=>setReview(p)}>Record review</button>}</td></tr>)}</tbody></table></div>{!data.policies.length&&<p className="empty">No policies uploaded.</p>}</section></>;
}

export function NotificationsPage({principal}){
 const admin=principal.permissions.includes('account:manage'),manage=principal.permissions.includes('action:manage');
 const [items,setItems]=useState([]),[settings,setSettings]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setItems((await api('/notifications')).notifications);if(manage)setSettings(await api('/reminders/settings'))}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function run(){setBusy(true);setError('');try{const result=await api('/reminders/run',json('POST',{}));await load();setNotice(`${result.delivered} new notifications delivered.`)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(event){event.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try{setSettings(await api('/reminders/settings',json('PUT',{enabled:values.enabled==='on',upcomingDays:Number(values.upcomingDays),repeatDays:Number(values.repeatDays)})));setNotice('Reminder settings saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function read(id){try{await api(`/notifications/${id}/read`,json('POST',{}));await load()}catch(e){setError(e.message)}}
 return <><p className="eyebrow">Stay on track</p><h1>Notifications</h1><p className="subtitle">Your action and policy-review reminders. Notifications are delivered here automatically while the application server is running.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{manage&&<button disabled={busy} onClick={run}>Check reminders now</button>}
 {admin&&settings&&<section className="panel"><h2>Reminder settings</h2><form className="record-form" onSubmit={save}><Field>Delivery<select name="enabled" defaultValue={settings.enabled?'on':'off'}><option value="on">Enabled</option><option value="off">Disabled</option></select></Field><Field>Days before due date<input type="number" name="upcomingDays" min="1" max="365" required defaultValue={settings.upcomingDays}/></Field><Field>Repeat overdue reminders every (days)<input type="number" name="repeatDays" min="1" max="365" required defaultValue={settings.repeatDays}/></Field><button disabled={busy} className="primary">Save reminders</button></form><p className="form-note">Due-today reminders are included. Overdue reminders begin one day after the deadline. Dates use UTC.</p></section>}
 <section className="panel"><h2>My inbox</h2>{!items.length&&<p className="empty">No notifications yet.</p>}{items.map(n=><article className="notification" key={n.id}><h3>{n.title}</h3><p>{n.message}</p><small>{n.delivered_at} · {n.read_at?'Read':'Unread'}</small>{!n.read_at&&<button onClick={()=>read(n.id)}>Mark as read</button>}</article>)}</section></>;
}

export function SecurityPage({principal,onChanged}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event){event.preventDefault();setError('');const b=Object.fromEntries(new FormData(event.currentTarget));if(b.newPassword!==b.confirm){setError('New passwords must match.');return}setBusy(true);try{await api('/auth/password',json('POST',{currentPassword:b.currentPassword,newPassword:b.newPassword}));onChanged()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><p className="eyebrow">Account security</p><h1>Change password</h1><p className="subtitle">{principal.mustChangePassword?'Your password was reset. Choose a new password before continuing.':'Changing your password signs you out on all devices.'}</p>{error&&<p className="error" role="alert">{error}</p>}<section className="panel"><form className="admin-form" onSubmit={submit}><FormNote/><Field>Current password<input type="password" name="currentPassword" autoComplete="current-password" required/></Field><Field>New password<input type="password" name="newPassword" autoComplete="new-password" required minLength="12" maxLength="200"/></Field><Field>Confirm password<input type="password" name="confirm" autoComplete="new-password" required minLength="12" maxLength="200"/></Field><button className="primary" disabled={busy}>Change password and sign out</button></form></section></>;
}
